version: '3.7'

services:
  #cedar-servcer:
  #  build: .
  #  environment:
  #    RUST_LOG: debug
  #    GRPC_API_ADDR: 0.0.0.0:50051
  #    DATABASE_URL: postgres://postgres:local_only@postgres/cedar
  #  networks:
  #    - cedar-server
  #  ports:
  #    - "50051:50051"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "local_only"
      POSTGRES_DB: "cedar_server"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - cedar-server
    ports:
      - "5432:5432"

networks:
  cedar-server:
